version: 0.2
phases:
  install:
    runtime-versions: { python: 3.10 }
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest
  build:
    commands:
      - pytest -q
artifacts:
  files: ['test-results.txt']
